development:
  host: <%= ENV["MONGOLAB_POPOS_HOST"] %>
  port: <%= ENV["MONGOLAB_POPOS_PORT"] %>
  database: <%= ENV["MONGOLAB_POPOS_DATABASE"] %>
  username: <%= ENV["MONGOLAB_POPOS_USERNAME"] %>
  password: <%= ENV["MONGOLAB_POPOS_PASSWORD"] %>

test:
  host: localhost
  database: popos_test

production:
  host: <%= ENV["MONGOLAB_POPOS_HOST"] %>
  port: <%= ENV["MONGOLAB_POPOS_PORT"] %>
  database: <%= ENV["MONGOLAB_POPOS_DATABASE"] %>
  username: <%= ENV["MONGOLAB_POPOS_USERNAME"] %>
  password: <%= ENV["MONGOLAB_POPOS_PASSWORD"] %>
